{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-europepmc
  version: {{ version|replace("-", "_") }}

source:
  fn: europepmc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/europepmc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/europepmc/europepmc_{{ version }}.tar.gz
  sha256: c1ba91a2a99432cabe18e86fea33ac9d20dbb3ac0b58f430d464b4d8ecba4a9a

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-plyr
    - r-progress
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-urltools
    - r-xml2
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-plyr
    - r-progress
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-urltools
    - r-xml2

test:
  commands:
    - $R -e "library('europepmc')"           # [not win]
    - "\"%R%\" -e \"library('europepmc')\""  # [win]

about:
  home: http://github.com/ropensci/europepmc/
  license: GPL-3.0-only
  summary: An R Client for the Europe PubMed Central RESTful Web Service (see <https://europepmc.org/RestfulWebService> for more information). It gives access to both metadata on life science literature and open access full texts. Europe PMC indexes all PubMed content and other literature sources including Agricola, a bibliographic
    database of citations to the agricultural literature, or Biological Patents. In addition to bibliographic metadata, the client allows users to fetch citations and reference lists. Links between life-science literature and other EBI databases, including ENA, PDB or ChEMBL are also accessible. No registration or API key
    is required. See the vignettes for usage examples.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
