appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Zn0lREBnmbc1u/O7yd4FZxKan+h2bJeSdIPoKCLmO29Irf1xJwkknyg7AioHIhzHXKOwDivp8qWYpkAhYtq1rLDp7cXFvHOGbn5VuujAb8nM67C8qXehfZYS7v73zCDczFZ5s5fgP0CjXp6FnJrMpT5fSEM47tH1RwDcQ04cFgQnKwvcn/nvuUqP1SgjoJznKgYBx8xZBLSJ8MVxrNUmORe8nhUx8SyO8B3JP1K4P1BiBFm6fuJpf7Fv2DtJ8v2eT2J63wzhKJUFmATGZ2+HY7hwmp8EXDdf1F64eVktkr9QuXWAx848OgsuuRe1Kr7wqop+Ik1ViyZE+9gwdRuE+Dpdk1kcRUf5nDsOHEPQpQbFBNPrRKmmbRy8fOM7RTBeqnXN+6OYgXSjO7yGAfgZvuAaZFSsMP/emyMe5lEm4j2iy49KNO4avTOdjTSzkPASBStppH5t4IXV8DLR3wIUA/Gif3Kr2w/pt8kfmQXOHm57cy06I161+3IWIUzxIYBpLS0cQOttign9y1jfYTtgx7l8kFnNEdZKg8Mg5rfRKYznsm+Mt6evw3zy2AWk1Ql2ohj8PjH673e9/LyBKO9MmtjSAlxe3fc7wD9SMVqiOAppgLDz3p6xK/HcKqXNUxIngSa6EOeMXbyIOfDCn9bcoJekDgPhu8fPvEBMesDGl9w=}
